debug_mode: False
market_indexes:
  - "S&P 500" : "^GSPC"
  - "Dow Jones" : "^DJI"
  - "NASDAQ" : "^IXIC"
  - "NYSE" : "^NYA"
  - "CAC 40" : "^FCHI"
  - "NYCE Amex" : "^XAX"
  - "Russell 2000" : "^RUT"
  - "CBOE volatility" : "^VIX"
  - "FTSE 100" : "^FTSE" 
  - "Euronext 100" : "^N100"
  - "DAX" : "^GDAXI"
multi_symbols:
  - "top-low"
  - "down_tickers"
  - "in_market"
market_plots:
  - "panel signals": 
      name : "panel_signals.json"
      data_type : "plot"
  - "current state": 
      name: "market_message.json"
      data_type : "message"
  - "forecast" : 
      name: "forecast_plot.json"
      data_type : "plot"
  - "states scaled time series" : 
      name: "ts_hmm.json"
      data_type : "plot"
asset_plots:
  - "panel signals": 
      name: "panel_signals.json"
      data_type : "plot"
  - "current state": 
      name: "market_message.json"
      data_type : "message"
  - "states analysis" : 
      name: "hmm_analysis.json"
      data_type : "plot"
  - "states scaled time series" : 
      name: "ts_hmm.json"
      data_type : "plot"
signals:
  - "RSI": "RSI"
  - "rel_MA_spread" : "Moving Averages"
  - "pair_z_score": "Pairs"
  - "ROC": "ROC"
  - 'STOCHOSC': 'STOCHOSC'


local_tmps: "C:/Users/Miguel/virgo_api/research_env/tmp_plots"
local_tmps_market_research: "C:/Users/Miguel/virgo_api/research_env/tmp_plots/tmp_market"  
local_tmps_asset_research: "C:/Users/Miguel/virgo_api/research_env/tmp_plots/tmp_asset" 

models:
  - "sirius":
      description: "Sirius is a ML model trained using a sample of 40 symbols. It is a generic ML model to detect positives and negatives edges returns in the coming 30  days and the result is given as a binary classfiication in a two output model"