debug_mode: False
market_indexes:
  - "S&P 500" : "^GSPC"
  - "Dow Jones" : "^DJI"
  - "NASDAQ" : "^IXIC"
  - "NYSE" : "^NYA"
  - "CAC 40" : "^FCHI"
  - "NYCE Amex" : "^XAX"
  - "Russell 2000" : "^RUT"
  - "CBOE volatility" : "^VIX"
  - "FTSE 100" : "^FTSE" 
  - "Euronext 100" : "^N100"
  - "DAX" : "^GDAXI"
multi_symbols:
  - "top-low"
  - "down_tickers"
  - "in_market"
market_plots:
  - "panel signals": "panel_signals.json"
  - "forecast" : "forecast_plot.json"
  - "states analysis" : "hmm_analysis.json"
  - "states scaled time series" : "ts_hmm.json"
asset_plots:
  - "panel signals": "panel_signals.json"
  - "states analysis" : "hmm_analysis.json"
  - "states scaled time series" : "ts_hmm.json"
signals:
  - "RSI"
  - "rel_MA_spread"
  - "pair_z_score"
local_tmps: "C:/Users/Miguel/virgo_api/research_env/tmp_plots"
local_tmps_market_research: "C:/Users/Miguel/virgo_api/research_env/tmp_plots/tmp_market"  
local_tmps_asset_research: "C:/Users/Miguel/virgo_api/research_env/tmp_plots/tmp_asset"  